name: CI
on:
  pull_request:
    types:
      - opened
      - synchronize
    branches:
      - master
  push:
    branches:
      - master

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

permissions:
  contents: read # to fetch code (actions/checkout)

jobs:
  tests:
    name: Run tests
    runs-on: ubuntu-latest
    if: github.repository == 'luci-digital/lucia_tooling_omzsh'
    steps:
      - name: Harden the runner (Audit all outbound calls)
        uses: step-security/harden-runner@9af89fc71515a100421586dfdb3dc9c984fbf411 # v2.19.4
        with:
          egress-policy: audit

      - name: Set up git repository
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - name: Install zsh
        run: sudo apt-get update; sudo apt-get install zsh
      - name: Check legacy OMZ syntax
        run: |
          for file in ./modules/legacy/original-layout/oh-my-zsh.sh \
                      ./modules/legacy/original-layout/lib/*.zsh \
                      ./modules/legacy/original-layout/plugins/*/*.plugin.zsh \
                      ./modules/legacy/original-layout/plugins/*/_* \
                      ./modules/legacy/original-layout/themes/*.zsh-theme; do
            zsh -n "$file" || return 1
          done
      - name: Check sovereign shell syntax
        run: |
          for file in ./modules/shell/zshrc/.zshrc \
                      ./modules/shell/zshrc/*.zsh; do
            [ -f "$file" ] && { zsh -n "$file" || return 1; }
          done
